Update to chai 1.3.x
This version has better output for differences when using the deepEqual
assertion. The old 1.2.x line would report:

    expected [ Array(3) ] to deeply equal [ Array(3) ]

The 1.3.x line reports the same failure as:

    AssertionError: [["F"],["D","E"],["A","B","C"]] deepEqual [["A","B","C"],["D","E"],["F"]]